# Generated by Django 2.0.3 on 2018-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180323_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='to_date',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=2018, max_length=2000),
            preserve_default=False,
        ),
    ]
