# Generated by Django 2.0.3 on 2018-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='to_date',
        ),
        migrations.AddField(
            model_name='experience',
            name='year',
            field=models.CharField(default='2018', max_length=2000),
            preserve_default=False,
        ),
    ]
